stages:
   - build
   - Build Docker Image
   - Login & Push Docker Image
   - deploy on eks
build-job:
   stage: build
   tags: 
      - test-runner  #gitlab-Runner Tag to run project on that specific tag
   script:
     - echo "python build started"
     - "pip install -r requirements.txt"

dockerimage-job:
   stage: Build Docker Image
   tags: 
      - test-runner
   script:
     - echo "Building Docker image"
     - "docker info"
     - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 667684916769.dkr.ecr.us-west-2.amazonaws.com
     - docker build -t 667684916769.dkr.ecr.us-west-2.amazonaws.com/python-app .
dockerlogin and push -job:
   stage: Login & Push Docker Image
   tags: 
      - test-runner
   before_script:
     - echo "login to ECR"
     - "aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 667684916769.dkr.ecr.us-west-2.amazonaws.com"
    # - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWD"
    # - docker login registry.gitlab.com -u 00farhan00 -p $CICD_TOKEN
   script:
      - echo "docker push image"
      - docker push 667684916769.dkr.ecr.us-west-2.amazonaws.com/python-app:latest
     # - docker push farhanregistery/python-application
     # - docker push registery.gitlab.com/00farhan00/maven-web-app

deploy on eks:
   stage: deploy on eks
   tags: 
      - test-runner #gitlab- Runner Tag to run project on that specific tag
   script:
     - echo "deployment on eks cluster started"
     - "kubectl apply -f manifest.yml"
     - "kubectl get pods"
     - "kubectl get svc"
